coder:
  env:
    - name: CODER_PG_CONNECTION_URL
      valueFrom:
        secretKeyRef:
          name: coder-db-url
          key: url

    - name: CODER_ACCESS_URL
      value: "https://timgcp.demo.coder.com"
    - name: CODER_WILDCARD_ACCESS_URL
      value: "*.timgcp.demo.coder.com"

    - name: CODER_OIDC_ISSUER_URL                                               
      value: "https://gitlab.com"                                               
    - name: CODER_OIDC_EMAIL_DOMAIN                                             
      value: "coder.com"                                                        
    - name: CODER_OIDC_CLIENT_ID                                                
      valueFrom:
        secretKeyRef:
          name: coder-oidc-client-id
          key: value
    - name: CODER_OIDC_CLIENT_SECRET     
      valueFrom:
        secretKeyRef:
          name: coder-oidc-client-secret
          key: value                                       

    - name: CODER_BROWSER_ONLY
      value: "true"

  tls:
    secretNames:
      #wildcard cert for both the ACCESS_URL and WILDCARD_ACCESS_URL
      - bothdomains

  nodeSelector: 
    tier: ctrlplane

  tolerations:
  - key: "tier"
    operator: "Equal"
    value: "ctrlplane"
    effect: "NoSchedule"

  replicaCount: 1
  
  image:
    pullPolicy: IfNotPresent
    tag: "v2.3.3"